# Generated by Django 5.0 on 2024-02-13 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['name', 'owner', 'description'], 'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
    ]
